
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/srcres258/CreativePageJump"
authors="${mod_authors}"
displayTest="IGNORE_ALL_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    type="required" # NeoForge recognises this
    mandatory=true # Forge recognises this
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required" # NeoForge recognises this
    mandatory=true # Forge recognises this
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="mixins.creativepagejump.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
